Create Table Job_Applications(
user_id number primary key,
job_id number,
date_applied date,
f_name varchar(30),
l_name varchar(30),
address varchar(50),
city varchar(30),
state_us varchar(30),
country varchar(30),
zip char(5),
date_of_birth date,
phone_number varchar(10),
email varchar(30),
school_attended varchar(30),
degree varchar(20),
major varchar(20),
grad_date date,
gpa number,
company_name varchar(30),
job_title varchar(30),
date_started date,
date_ended date,
work_eligibility varchar(3),
);